services:

  db:
    image: postgres:18
    container_name: jobfinder-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}

    volumes:
      - jobfinder_postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  api:
    build:
      context: ./python-services
      dockerfile: Dockerfile

    env_file: ./python-services/.env

    container_name: jobfinder-api
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      LLM_BASE_URL: ${LLM_BASE_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL}
      LLM_FALLBACK_MODELS: ${LLM_FALLBACK_MODELS}

    depends_on:
      db:
        condition: service_healthy

  scraper:
    build:
      context: ./python-services
      dockerfile: Dockerfile.scraper

    env_file: ./python-services/.env

    container_name: jobfinder-scraper
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SCRAPER_INTERVAL_MINUTES: 360

    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: JobFinder/Dockerfile

    container_name: jobfinder-web
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      Services__PythonApiBaseUrl: "http://api:8000/"

    ports:
      - "7176:8080"

    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started


volumes:
  jobfinder_postgres_data:
